TRUNCATE TABLE fact_sales RESTART IDENTITY;
TRUNCATE TABLE dim_customer RESTART IDENTITY CASCADE;
TRUNCATE TABLE dim_product_category RESTART IDENTITY CASCADE;
TRUNCATE TABLE dim_date RESTART IDENTITY CASCADE;
